505:
502:
500:
416:
412:
410:
408:
406:
405:
404:
  body:
    application/json:
      example: |
        {"message": "<<resourcePathName|!singularize>> not found" }
403:
401:
400:
304:
303:
301:
204:
200:
  body:
    application/json:
      example: |
        <<exampleCollection>>
